### ISSUE TITLE
add generation tool

### ISSUE THREAD

**Issue by matkoniecz** [b-jazz/sharp-turns-onto-ramps#1]
would be a good idea to publish also code to generate these maps

**Comment by b-jazz** [comment]
I was hoping that the project would grab more attention and traction and it would turn into something that many people were interested in and advanced the project, but it looks like it (and the original project by the diary entry that started it all) has languished and isn't being actively pursued. Therefore, I won't be working on adding anything more to this or checking in hacks that would need extra work and documentation for someone to gain anything out of it. Sorry.
